/**
 * 定义所有可操作的Handler 常量
 * @module
 */ /** */
export const SET_WEB_TITLE = 'setWebTitle'
export const CHOOSE_IMG = 'chooseImg'
export const MAKE_CALL_TO_NUMBER = 'makeCallToNumber'
export const SEND_SMS_TO_NUMBER = 'sendSmsToNumber'
export const OPEN_MAIL = 'openMail'
export const OPEN_URL = 'openUrl'
export const OPEN_CONTACT_ITEM = 'openContactItem'
export const OPEN_CONTACT = 'openContact'
export const SET_BAR_COLOR = 'setBarColor'
export const SET_BAR_VISIBLE = 'showBar'
export const SET_BAR_VISIBLE_PC = 'showMenu'
export const SET_BAR = 'setBar'
export const EXIT = 'exitWebApp'
export const OPEN_DATE = 'openDate'
export const GET_LOCATION = 'getLocation'
export const API_INFOS = 'apiList'
export const SCAN_QRCODE = 'scanQRCode'
export const SHARE_TO = 'shareTo'
export const OPEN_DIALOG = 'openDialog'
export const SELECT_SESSION = 'selectSession'
export const GET_LANGUAGE = 'getLanguage'
export const WINDOW_CLOSE = 'windowClose'
export const PAGE_GO_BACK = 'pgGoBack'

// 1.1
export const PREVIEW_IMG = 'previewImg'
export const OPEN_FILE = 'openFile'
export const ADD_MENU_ITEM = 'addMenuItem'
export const REMOVE_MENU_ITEM = 'removeMenuItem'
export const SET_NATIVE_MENU_ITEM = 'setNativeMenuItem'
export const GEO_NAVIGATE = 'geoNavigate'
